name = "recipe-ui"
compatibility_date = "2023-12-01"
node_compat = true


[[kv_namespaces]]
binding = "AUTH_SESSION"
id = "7432226397d743b4b82fec98a9a7286b"

[vars]
SEARCHINDEX = "recipes"
SEARCHHOST = "https://search.roadsign.pictures"
SQL_URL = "libsql://recipe-zmaillard.turso.io"
AUTH0_CLIENTID = "zfOtjqVGMEufqrtnnBuMyDCV17iE4HSi"
AUTH0_DOMAIN = "sagebrushgis.auth0.com"
AUTH0_CALLBACK = "https://recipesear.ch/callback"
AUTH0_AUDIENCE = "https://bot.recipesear.ch"
