name = "recipe-ui"
compatibility_date = "2023-12-01"
node_compat = true

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "AUTH_SESSION"
id = "7432226397d743b4b82fec98a9a7286b"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
